dist: xenial

language: php

php:
  - '7.2'
  - '7.3'

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database concern_app_testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

deploy:
  # deploy develop to the development environment
  - provider: script
    script: chmod +x ./scripts/deploy_dev.sh
    on:
      branch: dev
  # deploy master to production
  - provider: script
    script: chmod +x scripts/deploy_prod.sh
    on:
      branch: master