dist: xenial

language: php

php:
  - '7.2'
  - '7.3'

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database concern_app_testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

after_success:
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then wget "'https://forge.laravel.com/servers/264031/sites/705525/deploy/http?token='$FORGE_DEVELOPMENT_TOKEN"; fi